lan_profile:
    resource: "@LanProfileBundle/Controller/"
    type:     annotation
    prefix:   /

lan_core:
    resource: "@LanCoreBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"