<?php

namespace Lan\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrivacyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivacyRepository extends EntityRepository
{
}
