<?php

namespace Lan\TournamentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TournamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    public function checkTeamFromTournament($teamPlayer, $tournament)
     {
         return $this->getEntityManager()
             ->createQuery('SELECT t FROM LanTournamentBundle:Team t
           
                             WHERE t.parentTeam = :teamPlayer 
                        ')
             ->setParameters(array(
                 'teamPlayer' => $teamPlayer->getId()
             ))
             ->getResult();
     }
}
